name: Daily_Report_Briefing
on:
  schedule:
    - cron: '15 21 * * *' # 한국 시간 오전 6시 15분 (UTC 21:15)

  workflow_dispatch:
jobs:
  run-daily-briefing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install requests
      - env:
          PUBLIC_DATA_API_KEY: ${{ secrets.PUBLIC_DATA_API_KEY }}
          NAVER_CLIENT_ID: ${{ secrets.NAVER_CLIENT_ID }}
          NAVER_CLIENT_SECRET: ${{ secrets.NAVER_CLIENT_SECRET }}
          NAVER_ADDRESS: ${{ secrets.NAVER_ADDRESS }}
          NAVER_PASSWORD: ${{ secrets.NAVER_PASSWORD }}
          REPORT_RECIPIENTS: ${{ secrets.REPORT_RECIPIENTS }}
          GH_PAT: ${{ secrets.GH_PAT }}
        run: python Daily_Report_Briefing.py
